### PR TITLE
Move ELM code to code/

### LINKED ISSUE #208: pub type Frame<'a> from the docs not working.
Hello Guys,
I am studying the docs of `ratatui` and I am pretty new to Rust in general. I cant create the type of the Elm architecture part:
https://ratatui.rs/concepts/application-patterns/the-elm-architecture/

## To Reproduce

Copy the whole example into vs code with rust-analyzer. `cargo build` produces the same error message. 
grafik

## Expected behavior

I expect the examples from the docs to work.

## Environment

Add a description of the systems where you are observing the issue. For example:
- OS: Windows
- Terminal Emulator: Windows Terminal with Powershell 7.0
- Crate version: ratatui: 0.24.0, crossterm: 0.27.0
- Backend: crossterm
- cargo: 1.74

### PR DESCRIPTION
**Pull request by joshka**
Fixes #208

### CODE REVIEW

File: code/the-elm-architecture/src/main.rs [hunk 1]
```diff
@@ -0,0 +1,144 @@
...
+}
+// ANCHOR_END: view
+
+/// Convert Event to Message
+///
+/// We don't need to pass in a `model` to this function in this example
+/// but you might need it as your project evolves
+fn handle_event(_: &Model) -> anyhow::Result<Option<Message>> {
+    let message = if event::poll(Duration::from_millis(250))? {
+        if let event::Event::Key(key) = event::read()? {
```
Comment (HenningCode) [inline code/the-elm-architecture/src/main.rs]: ` if key.kind == crossterm::event::KeyEventKind::Press` 

I would add this here to remove confusion about why the counter increments or decrements two on Windows.

Comment (joshka) [reply code/the-elm-architecture/src/main.rs]: done
